name: 'Release'

inputs:
  token:
    required: false
    default: ${{ github.token }}
  repository:
    required: false
    default: ${{ github.repository }}
  sha:
    required: false
    default: ${{ github.sha }}

runs:
  using: 'node20'
  main: 'index.js'
