name: action-create-release
description: create tag and release

branding:
  icon: cast
  color: red

inputs:

  token:
    required: false
    default: ${{ github.token }}

outputs:

  version:
    description: version string

runs:
  using: 'node20'
  main: 'index.js'
