name: release 

on:
  push:
    branches:
      - master 
    paths:
      - index.js
      - package.json
      - package-lock.json

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Set up source
        uses: actions/checkout@v4

      - name: Release
        uses: ./
